export enum CommentActionType {
    
    ADD_COMMENT = 'ADD_COMMENT',
    ADD_COMMENT_LIST = 'ADD_COMMENT_LIST',
    DELETE_COMMENT = 'DELETE_COMMENT',
    CLEAR_ALL_DATA_COMMENT = 'CLEAR_ALL_DATA_COMMENT',
    UPDATE_COMMENT = 'UPDATE_COMMENT',
    CLOSE_COMMENT_EDITOR = 'CLOSE_COMMENT_EDITOR',
    OPEN_COMMENT_EDITOR = 'OPEN_COMMENT_EDITOR',
    DB_FETCH_COMMENTS = 'DB_FETCH_COMMENTS',
    ASYNC_ADD_NEW_COMMENT = 'ASYNC_ADD_NEW_COMMENT',
    ASYNC_UPDATE_COMMENT = 'ASYNC_UPDATE_COMMENT',
    ASYNC_DELETE_COMMENT = 'ASYNC_DELETE_COMMENT',
    HAS_MORE_COMMENTS = 'HAS_MORE_COMMENTS',
    NO_MORE_COMMENTS = 'NO_MORE_COMMENTS'
}