export enum NotificationActionType {
    ADD_NOTIFY = 'ADD_NOTIFY',
    DB_FETCH_NOTIFICATIONS = 'DB_FETCH_NOTIFICATIONS',
    ADD_NOTIFY_LIST = 'ADD_NOTIFY_LIST',
    SG_SEEN_NOTIFICATION = 'SG_SEEN_NOTIFICATION',
    SG_SEEN_ALL_NOTIFICATIONS = 'SG_SEEN_ALL_NOTIFICATIONS',
    SEEN_ALL_NOTIFICATIONS = 'SEEN_ALL_NOTIFICATIONS',
    ADD_PLAIN_NOTIFY_LIST = 'ADD_PLAIN_NOTIFY_LIST',
    DELETE_NOTIFY = 'DELETE_NOTIFY',
    SEEN_NOTIFY = 'SEEN_NOTIFY',
    CLEAR_ALL_DATA_NOTIFY = 'CLEAR_ALL_DATA_NOTIFY',
}
