export enum ServerActionType {
    SET_REQUEST = 'SET_REQUEST',
    DELETE_REQUEST = 'DELETE_REQUEST',
    ERROR_REQUEST = 'ERROR_REQUEST',
    OK_REQUEST = 'OK_REQUEST',
    CLEAR_ALL_DATA_REQUEST = 'CLEAR_ALL_DATA_REQUEST',
}
