export enum UserSettingActionType {
    SET_USER_SETTING = 'SET_USER_SETTING',
    UPDATE_USER_SETTING = 'UPDATE_USER_SETTING',
    DB_UPDATE_USER_SETTING = 'DB_UPDATE_USER_SETTING',
    DB_FETCH_USER_SETTING = 'DB_FETCH_USER_SETTING',
    CLEAR_ALL_USER_SETTING = 'CLEAR_ALL_USER_SETTING',
    CHANGE_CURRENT_LANG = 'CHANGE_CURRENT_LANG',
    SET_CURRENT_LANG_FROM_COOKIE = 'SET_CURRENT_LANG_FROM_COOKIE',
}
