export enum VoteActionType {
    ADD_VOTE = 'ADD_VOTE',
    DELETE_VOTE = 'DELETE_VOTE',
    ADD_VOTE_LIST = 'ADD_VOTE_LIST',
    CLEAR_ALL_DATA_VOTE = 'CLEAR_ALL_DATA_VOTE',
    ASYNC_ADD_NEW_VOTE = 'ASYNC_ADD_NEW_VOTE',
    ASYNC_DELETE_VOTE = 'ASYNC_DELETE_VOTE',
}
